filebeat:
  prospectors:
    -
      paths:
        - /var/log/nginx/*.log
      document_type: nginx-access
    -
      paths:
        - /var/log/syslog
        - /var/log/auth.log
      document_tyoe: syslog

  registry_file: /var/lib/filebeat/registry

output:
#  elasticsearch:
#    hosts: ["localhost:9200"]
  logstash:
    hosts: ["logstash:5044"]
    #worker: 1
    #compression_level: 3
    #loadbalance: true
shipper:
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
